---
- name: check if {{ ethernet }} exist
  shell: |
    ip addr show | grep -E '^[0-9]+: {{ ethernet }}:' | wc -l
  when: ethernet is defined and ethernet != ""
  register: ethernet_find
- debug: msg="ethernet_find = {{ ethernet_find }}"
  when: debug
- name: configuring public network (ubuntu flavour)
  include: ./public-networking-ubuntu.yaml
  when: |
    ansible_distribution == "Ubuntu" and
    ethernet_find is defined and
    ethernet_find.stdout|int > 0
- name: configuring public network (redhat flavour)
  include: ./public-networking-rdo.yaml
  when: |
    ansible_os_family == "RedHat" and
    ethernet_find is defined and
    ethernet_find.stdout|int > 0
