---
- hosts: {{hosts}}
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name:
      include: ./public-networking-ubuntu.yaml ethernet={{ethernet}}
      when: |
      ansbile_distribution == "Ubuntu" and
      ethernet is defined and
      ethernet != ""
