---
- name: check if {{ ethernet }} exist
  shell: |
    ip addr show | grep -E '^[0-9]+: {{ ethernet }}:' | wc -l
  when: ethernet is defined and ethernet != ""
  register: ethernet_find
- name:
  include: ./public-networking-ubuntu.yaml ethernet={{ ethernet }}
  when: |
    ansbile_distribution == "Ubuntu" and
    ethernet_find is defined and
    {{ ethernet_find.stdout | int }} > 0
- name:
  include: ./public-networking-rdo.yaml ethernet={{ ethernet }}
  when: |
    ansible_os_family == "RedHat" and
    ethernet_find is defined and
    {{ ehternet_find.stdout | int }} > 0
