---
- name: ensure software-properties-common is installed on {{ hosts }}
  apt: name=software-properties-common update_cache=yes
  when: ansible_distribution == "Ubuntu"
- name: ensure mariadb apt key is present (ubuntu)
  apt_key: |
    url=keyserver.ubuntu.com:80
    id=0xF1656F24C74CD1D8
  when: ansible_distribution == "Ubuntu"
- name: |
    ensure mariadb {{ sql-version }} repository is present (ubuntu
    {{ ansible_distribution_release }})
  apt_repository: |
    repo="deb [arch=amd64,i386,ppc64el]
    http://mariadb.mirror.digitalpacific.com.au/repo/{{ sql-version }}/ubuntu
    {{ ansible_distribution_release }} main" update_cache=yes
  when: |
    ansible_distribution == "Ubuntu" and
    (ansible_distribution_release == "trusty" or
    ansible_distribution_release == "xenial")
- name: |
    ensure mariadb {{sql-version}} repository is present (ubuntu
    {{ ansible_distribution_release }})
  apt_repository: |
    repo="deb [arch=amd64,i386]
    http://mariadb.mirror.digitalpacific.com.au/repo/{{ sql-version }}/ubuntu
    {{ ansible_distribution_release }} main" update_cache=yes
  when: |
    ansible_distribution == "Ubuntu" and
    (ansible_distribution_release == "willy" or
    ansible_distribution_release == "precise")
- name: install mariadb {{sql-version}} sql server (ubuntu)
  apt: name=mariadb-server
  when: ansible_distribution == "Ubuntu"
- name: ensure mariadb is configured correctly on {{ hosts }}
  blockinfile:
    dest: /etc/mysql/conf.d/openstack.cnf
    owner: root
    group: root
    block: |
      [mysqld]
      bind-address = 0.0.0.0
      default-storage-engine = innodb
      innodb_file_per_table
      max_connections = 4096
      collation-server = utf8_general_ci
      character-set-server = utf8
    create: yes
- name: ensure mariadb is restarted
  service: |
  name=mariadb-server state=restarted
